### ISSUE TITLE
openslam-gmapping: error: no match for 'operator==' in do_compile with glibc-2.26

### ISSUE THREAD

**Issue by bulwahn** [ros/meta-ros#539]
Since d6a0bc57fa07d887a78aa8ed76e3bf4558dc5127@openembedded/openembedded-core (glibc: Upgrade to 2.26 final release), `bitbake openslam-gmapping` fails in do_compile with:
```  
| In file included from /home/lukas/work/repositories/openembedded.org/openembedded-core/build/tmp-glibc/work/i586-oe-linux/openslam-gmapping/0.1.1-r0/openslam_gmapping-0.1.1/include/gmapping/utils/point.h:3:0,
|                  from /home/lukas/work/repositories/openembedded.org/openembedded-core/build/tmp-glibc/work/i586-oe-linux/openslam-gmapping/0.1.1-r0/openslam_gmapping-0.1.1/gridfastslam/gfsreader.h:9,
|                  from /home/lukas/work/repositories/openembedded.org/openembedded-core/build/tmp-glibc/work/i586-oe-linux/openslam-gmapping/0.1.1-r0/openslam_gmapping-0.1.1/gridfastslam/gfsreader.cpp:2:
| /home/lukas/work/repositories/openembedded.org/openembedded-core/build/tmp-glibc/work/i586-oe-linux/openslam-gmapping/0.1.1-r0/openslam_gmapping-0.1.1/gridfastslam/gfsreader.cpp: In member function 'virtual void GMapping::GFSReader::RawOdometryRecord::read(std::istream&)':
| /home/lukas/work/repositories/openembedded.org/openembedded-core/build/tmp-glibc/work/i586-oe-linux/openslam-gmapping/0.1.1-r0/openslam_gmapping-0.1.1/gridfastslam/gfsreader.cpp:79:3: error: no match for 'operator==' (operand types are 'std::istream {aka std::basic_istream<char>}' and 'int')
|    assert(is);
|    ^
```

**Comment by bulwahn** [comment]
I have already addressed the issue, submitted a patch upstream (https://github.com/ros-perception/openslam_gmapping/pull/19) and will provide a pull request here on meta-ros as well as soon as I am done running my local test build.
