### PR TITLE
socketcan-interface: patch CMakeLists.txt (resolves #574)

### LINKED ISSUE #574: socketcan-interface: fails with linker problem (after pull request #573)
Hi everyone,
Here is the error log message i have got today, the new added socketcan recipe failed when compiling. Does anyone know how to fix it?

Thanks 
Jay

```
| ERROR: oe_runmake failed
| ~/build/build/tmp/sysroots/x86_64-linux/usr/libexec/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/6.2.0/ld: CMakeFiles/socketcan_dump.dir/src/candump.cpp.o: undefined reference to symbol 'pthread_getspecific@@GLIBC_2.4'
| ~/build/build/tmp/sysroots/colibri-imx6/lib/libpthread.so.0: error adding symbols: DSO missing from command line
| collect2: error: ld returned 1 exit status
| make[2]: *** [CMakeFiles/socketcan_dump.dir/build.make:116: devel/lib/socketcan_interface/socketcan_dump] Error 1
| make[2]: Leaving directory '~/build/build/tmp/work/colibri_imx6-poky-linux-gnueabi/socketcan-interface/0.6.8-r0/build'
| make[1]: *** [CMakeFiles/Makefile2:172: CMakeFiles/socketcan_dump.dir/all] Error 2
| make[1]: Leaving directory '~/build/build/tmp/work/colibri_imx6-poky-linux-gnueabi/socketcan-interface/0.6.8-r0/build'
| make: *** [Makefile:131: all] Error 2
| WARNING: ~/build/build/tmp/work/colibri_imx6-poky-linux-gnueabi/socketcan-interface/0.6.8-r0/temp/run.do_compile.146847:1 exit 1 from 'exit 1'
| ERROR: Function failed: do_compile (log file is located at ~/build/build/tmp/work/colibri_imx6-poky-linux-gnueabi/socketcan-interface/0.6.8-r0/temp/log.do_compile.146847)
NOTE: recipe socketcan-interface-0.6.8-r0: task do_compile: Failed
ERROR: Task (~/build/poky/meta-ros/recipes-ros/ros-canopen/socketcan-interface_0.6.8.bb:do_compile) failed with exit code '1'
```

### PR DESCRIPTION
**Pull request by bulwahn**

### CODE REVIEW

**Comment by bulwahn** [comment]
`bitbake core-image-ros-world` builds successful on this build configuration:
```
Build Configuration:
BB_VERSION           = "1.37.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-16.04"
TARGET_SYS           = "arm-oe-linux-gnueabi"
MACHINE              = "qemuarm"
DISTRO               = "nodistro"
DISTRO_VERSION       = "nodistro.0"
TUNE_FEATURES        = "arm armv5 thumb dsp"
TARGET_FPU           = "soft"
meta                 = "HEAD:9daf88713dedfb29fe926e18d76090a6b2582ac8"
meta-oe              
meta-multimedia      
meta-python          = "master:6f536298c1afcaaff2771c7d0f242259d6b9fc1f"
meta-ros             = "ros-canopen-fixup:c857d2b26e178740b674324d437f19e2b94fb2f0"
```

**Comment by bulwahn** [comment]
I just rebased this commit and now CI is re-triggered.

**Comment by rojkov** [comment]
Looks good to me and CI is green. Merging...
